"""initial

Revision ID: 82527c824c6c
Revises: 
Create Date: 2022-05-28 20:47:19.558695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82527c824c6c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('nickname', sa.String(), nullable=False),
    sa.Column('battletag', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('battletag')
    )
    op.create_table('tournaments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('battlefy_id', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('region', sa.Enum('ASIA', 'EUROPE', 'AMERICAS', name='regionenum'), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='tournamentstatusenum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tournament_players',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('tournament_id', sa.BigInteger(), nullable=True),
    sa.Column('player_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tournament_player_decks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('tournament_id', sa.BigInteger(), nullable=True),
    sa.Column('deck_string', sa.String(), nullable=True),
    sa.Column('archetype_predict', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournament_players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tournament_player_decks')
    op.drop_table('tournament_players')
    op.drop_table('tournaments')
    op.drop_table('players')
    # ### end Alembic commands ###
